export const originalData = [
  {
    firstName: "Brooke",
    lastName: "Heeran",
    email: "bheeran0@altervista.org",
    gender: "Female",
    status: "Failed",
    type: "Batch Execution",
    department: "Risk Analysis",
    priority: "Urgent",
    creation_date: "08/30/2023",
  },
  {
    firstName: "Frazer",
    lastName: "Cathro",
    email: "fcathro1@ucla.edu",
    gender: "Male",
    status: "Failed",
    type: "Test Function",
    department: "Risk Analysis",
    priority: "Routine",
    creation_date: "08/25/2023",
  },
  {
    firstName: "Lemmie",
    lastName: "Ciric",
    email: {
      title: "lciric2@dmoz.org",
      metaList: ["First", "Second"],
    },
    gender: "Male",
    status: "Completed",
    type: "Batch Execution",
    department: "Claims",
    priority: "Subacute",
    creation_date: "08/20/2023",
  },
  {
    firstName: "Randy",
    lastName: "Boatwright",
    email: "rboatwright3@arstechnica.com",
    status: "Completed",
    gender: "Male",
    type: "Batch Execution",
    department: "Quality",
    priority: "Urgent",
    creation_date: "08/10/2023",
  },
  {
    firstName: "Rolando",
    lastName: "Cyples",
    email: "rcyples4@biglobe.ne.jp",
    gender: "Male",
    status: "Failed",
    type: "Batch Execution",
    department: "Claims",
    priority: "Routine",
    creation_date: "05/02/2023",
  },
  {
    firstName: "Lem",
    lastName: "Males",
    email: "lmales5@admin.ch",
    gender: "Male",
    status: "Failed",
    type: "Batch Execution",
    department: "Risk Analysis",
    priority: "Urgent",
    creation_date: "12/12/2023",
  },
  {
    firstName: "Sayres",
    lastName: "Adelberg",
    email: "sadelberg6@uol.com.br",
    gender: "Female",
    status: "Completed",
    type: "Test Function",
    department: "Risk Analysis",
    priority: "Urgent",
    creation_date: "08/03/2023",
  },
  {
    firstName: "Murray",
    lastName: "Bravington",
    email: "mbravington7@drupal.org",
    gender: "Male",
    status: "Failed",
    type: "Test Function",
    department: "Claims",
    priority: "Urgent",
    creation_date: "08/07/2023",
  },
  {
    firstName: "Jena",
    lastName: "Swatheridge",
    email: "jswatheridge8@npr.org",
    gender: "Female",
    status: "Failed",
    type: "Test Function",
    department: "Quality",
    priority: "Routine",
    creation_date: "08/02/2023",
  },
  {
    firstName: "Annabel",
    lastName: "Nelsey",
    email: "anelsey9@google.com",
    gender: "Female",
    status: "Completed",
    type: "Test Function",
    department: "Risk Analysis",
    priority: "Urgent",
    creation_date: "10/05/2023",
  },
  {
    firstName: "Carin",
    lastName: "Robiou",
    email: "crobioua@skype.com",
    gender: "Female",
    status: "Completed",
    type: "Test Function",
    department: "Risk Analysis",
    priority: "Routine",
    creation_date: "12/26/2023",
  },
  {
    firstName: "Anson",
    lastName: "Gamon",
    email: "agamonb@economist.com",
    gender: "Male",
    status: "Failed",
    type: "Test Function",
    department: "Risk Analysis",
    priority: "Routine",
  },
  {
    firstName: "Brina",
    lastName: "Pirie",
    email: "bpiriec@stumbleupon.com",
    gender: "Female",
    status: "Failed",
    type: "Test Function",
    department: "Risk Analysis",
    priority: "Routine",
  },
  {
    firstName: "Hermy",
    lastName: "Dyett",
    email: "hdyettd@boston.com",
    gender: "Male",
    status: "Failed",
    type: "Test Function",
    department: "Risk Analysis",
    priority: "Subacute",
  },
  {
    firstName: "Aime",
    lastName: "von Hagt",
    email: "avonhagte@nyu.edu",
    gender: "Female",
    status: "Failed",
    type: "Test Function",
    department: "Risk Analysis",
    priority: "Routine",
  },
  {
    firstName: "Wash",
    lastName: "Vannuchi",
    email: "wvannuchi1f@japanpost.jp",
    gender: "Male",
    status: "Failed",
    type: "Batch Execution",
    department: "Risk Analysis",
    priority: "Routine",
  },
  {
    firstName: "Nikki",
    lastName: "Faye",
    email: "nfaye1g@feedburner.com",
    gender: "Female",
    status: "Completed",
    type: "Batch Execution",
    department: "Risk Analysis",
    priority: "Routine",
  },
  {
    firstName: "Aron",
    lastName: "Scimonelli",
    email: "ascimonelli1h@nationalgeographic.com",
    gender: "Male",
    status: "Failed",
    type: "Batch Execution",
    department: "Risk Analysis",
    priority: "Subacute",
  },
  {
    firstName: "Smitty",
    lastName: "Giacomello",
    email: "sgiacomello1i@google.co.uk",
    gender: "Male",
    status: "Failed",
    type: "Batch Execution",
    department: "Risk Analysis",
    priority: "Subacute",
  },

  {
    firstName: "Annis",
    lastName: "Linkie",
    email: "alinkie2a@wp.com",
    gender: "Female",
    status: "Completed",
    type: "Batch Execution",
    department: "Claims",
    priority: "Subacute",
  },

  {
    firstName: "Cass",
    lastName: "Boot",
    email: "cboot2g@furl.net",
    gender: "Male",
    status: "Completed",
    type: "Batch Execution",
    department: "Risk Analysis",
    priority: "Subacute",
  },
  {
    firstName: "Montague",
    lastName: "Rossey",
    email: "mrossey2h@goo.gl",
    gender: "Male",
    status: "Completed",
    type: "Batch Execution",
    department: "Risk Analysis",
    priority: "Subacute",
  },
  {
    firstName: "Garrek",
    lastName: "Matignon",
    email: "gmatignon2r@noaa.gov",
    gender: "Male",
    status: "Failed",
    type: "Test Function",
    department: "Risk Analysis",
    priority: "Routine",
  },
];
