export const schema = [
  {
    name: "name",
    displayName: "Name",
    resizable: true,
    separator: true,
    tooltip: true,
    translate: (a) => ({
      title: `${a.firstName} ${a.lastName}`,
      firstName: a.firstName,
      lastName: a.lastName,
    }),
    cellType: "AVATAR_WITH_TEXT",
    width: "15%",
  },
  {
    name: "email",
    displayName: "Email",
    resizable: true,
    sorting: false,
    cellType: "WITH_META_LIST",
    width: "20%",
  },
  {
    name: "gender",
    displayName: "Gender",
    resizable: true,
    comparator: (a, b) => a.gender.localeCompare(b.gender),
    cellType: "STATUS_HINT",
    width: "10%",
    translate: (a) => ({
      title: a.gender,
      statusAppearance: a.gender === "Female" ? "alert" : "success",
    }),
  },
  {
    name: "type",
    displayName: "Type",
    sorting: false,
    cellType: "DEFAULT",
    width: "15%",
  },
  {
    name: "status",
    displayName: "Status",
    sorting: false,
    resizable: true,
    comparator: (a, b) => a.status.localeCompare(b.status),
    cellType: "STATUS_HINT",
    width: "15%",
    translate: (a) => ({
      title: a.status,
      statusAppearance: a.status === "Failed" ? "alert" : "success",
    }),
  },
  {
    name: "department",
    displayName: "Department",
    sorting: false,
    cellType: "DEFAULT",
    width: "15%",
  },
  {
    name: "priority",
    displayName: "Priority",
    sorting: false,
    cellType: "DEFAULT",
    width: "10%",
  },
];
